### ISSUE TITLE
Is there any document or example code?

### ISSUE THREAD

**Issue by HanqingWangAI** [tpmc/tpmc#1]
Hi, is there any demo code or manual?

**Comment by anuessing** [comment]
Hi. You can have a look at the repository at tpmc/tpmc-test where you can find test programs that reproduce the results presented in the paper, which you can find at https://doi.org/10.1145/3104989



Am 15. Juni 2018 08:33:07 GMT+01:00 schrieb qweas120 <notifications@github.com>:

**Comment by HanqingWangAI** [comment]
OK，thanks.
